
DROP TABLE RECENT_MEASURE;
CREATE TABLE RECENT_MEASURE AS
SELECT
t1.MEASURE_ID,
t1.MEASURE_NAME,
MAX(t1.MEASURE_START_DT) as MX_DT
FROM 
(
	SELECT
	T21.MEASURE_ID,
	T21.MEASURE_NAME,
	T21.MEASURE_START_DT
	FROM STG_CARE T21
	UNION ALL
	SELECT
	T22.MEASURE_ID,
	T22.MEASURE_NAME,
	T22.MEASURE_START_DT
	FROM STG_READMISSIONS T22
) T1
GROUP BY t1.MEASURE_ID,t1.MEASURE_NAME;

DROP TABLE MEASURE;
CREATE TABLE MEASURE(
	PROVIDER_ID INT,
	MEASURE_ID STRING,
	MEASURE_START_DT STRING,
	SCORE FLOAT
)
COMMENT 'Measure Data'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS ORC;

INSERT OVERWRITE TABLE MEASURE 
	SELECT DISTINCT 
		t11.PROVIDER_ID, 
		t11.MEASURE_ID, 
		t11.MEASURE_START_DT, 
		t11.SCORE
	FROM STG_CARE t11
	INNER JOIN RECENT_MEASURE t12
	on (t11.MEASURE_ID = t12.MEASURE_ID
	AND t11.MEASURE_START_DT = t12.MX_DT)
	UNION ALL
	SELECT DISTINCT 
		t21.PROVIDER_ID, 
		t21.MEASURE_ID, 
		t21.MEASURE_START_DT, 
		t21.SCORE
	FROM STG_READMISSIONS t21
	INNER JOIN RECENT_MEASURE t22
	on (t21.MEASURE_ID = t22.MEASURE_ID
	AND t21.MEASURE_START_DT = t22.MX_DT)
;