DROP TABLE SURVEY;
CREATE TABLE SURVEY(
	PROVIDER_ID INT,
	OVR_AP FLOAT
)
COMMENT 'Survey Data'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS ORC;

INSERT OVERWRITE TABLE SURVEY 
	SELECT 
		t11.PROVIDER_ID, 
		CASE
			 WHEN (SUBSTR(t11.OVR_AP,1,2) BETWEEN 1 AND 10) then SUBSTR(t11.OVR_AP,1,2) ELSE 5
		END as OVR_AP
	FROM STG_SURVEYS t11;