
DROP TABLE BEST_HOSPITALS;
CREATE TABLE BEST_HOSPITALS AS
SELECT
t1.PROVIDER_ID,
t1.HOSPITAL_NAME,
t1.STATE,
t1.TYPE_CD,
t1.OWNER_TYPE_CD,
t1.EMERGENCY_CD,
count(distinct t2.MEASURE_ID) as num_scores,
avg(case when t2.score > 100 then 100 else t2.score end) as avg_score
FROM HOSPITAL t1
INNER JOIN MEASURE t2
on t1.PROVIDER_ID = t2.PROVIDER_ID
GROUP BY t1.PROVIDER_ID, t1.HOSPITAL_NAME, t1.STATE, t1.TYPE_CD, t1.OWNER_TYPE_CD, t1.EMERGENCY_CD
ORDER BY AVG_SCORE DESC;