
	DROP TABLE SURVEY_CORR;
	CREATE TABLE SURVEY_CORR AS
	SELECT
	t1.PROVIDER_ID,
	t1.HOSPITAL_NAME,
	avg(case when t2.score > 100 then 100 else t2.score end) as avg_score,
	avg(t3.ovr_ap) as survey_score
	FROM HOSPITAL t1
	INNER JOIN MEASURE t2
	on t1.PROVIDER_ID = t2.PROVIDER_ID
	INNER JOIN SURVEY t3
	on t1.PROVIDER_ID = t3.PROVIDER_ID
	GROUP BY t1.PROVIDER_ID,t1.HOSPITAL_NAME
	ORDER BY AVG_SCORE DESC;
